routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth', 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
	Route::resource('game', 'GameController', ['except' => 'index']);
	Route::resource('group', 'GroupController');
	Route::get('match/{match}/game/', ['as' => 'match.game.get', 'uses' => 'MatchController@getCreateGame']);
	Route::resource('match', 'MatchController');
	Route::resource('season', 'SeasonController');
	Route::resource('team', 'TeamController');
	Route::resource('player', 'PlayerController');
	Route::resource('user', 'UserController');
	Route::get('/', 'IndexController@dashboard')->name('dashboard');
});

Route::get('/img/{path}', ['as' => 'img', 'uses' => 'ImageController@show'])->where('path', '.*');

Route::get('match/{matchId}', 'HomeController@match')->name('match');
Route::get('player/{playerId}', 'HomeController@player')->name('player');
Route::get('players', 'HomeController@players')->name('players');
Route::get('schedule', 'HomeController@schedule')->name('schedule');
Route::get('standings', 'HomeController@standings')->name('standings');
Route::get('team/{teamId}', 'HomeController@team')->name('team');
Route::get('teams', 'HomeController@teams')->name('teams');
Route::get('/', 'HomeController@index')->name('home');

app/Season.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\App;
use Laracasts\Presenter\PresentableTrait;

class Season extends Model
{
	use SoftDeletes;
	use PresentableTrait;
	
	/**
	 * The presenter class used to display data of this model.
	 *
	 * @var string
	 */
	protected $presenter = "App\Presenters\SeasonPresenter";
	
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'seasons';
	
	/**
	 * Attributes that should be mass-assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'start_date', 'end_date', 'created_at', 'updated_at', 'deleted_at'];
	
	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = [];
	
	/**
	 * The attributes that should be casted to native types.
	 *
	 * @var array
	 */
	protected $casts = [];
	
	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['start_date', 'end_date', 'created_at', 'updated_at', 'deleted_at'];
	
	/**
	 * Model's relationships
	 */
	public function groups ()
	{
		return $this->belongsToMany(Group::class, 'groups_seasons', 'season_id', 'group_id');
	}
	
	public function matches ()
	{
		return $this->hasMany(Match::class);
	}
	
	public function teams ()
	{
		return $this->belongsToMany(Team::class, 'teams_seasons', 'season_id', 'team_id');
	}
}

app/Http/Controllers/Admin/SeasonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Jobs\UpdateSeasonManagementJob;
use App\Repositories\Interfaces\GroupRepositoryInterface;
use App\Repositories\Interfaces\SeasonRepositoryInterface;
use App\Repositories\Interfaces\TeamRepositoryInterface;
use App\Services\GroupService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Laracasts\Utilities\JavaScript\JavaScriptFacade as JavaScript;

class SeasonController extends Controller
{
	/**
	 * @var SeasonRepositoryInterface
	 */
	private $repository;
	/**
	 * @var GroupRepositoryInterface
	 */
	private $groupRepository;
	/**
	 * @var TeamRepositoryInterface
	 */
	private $teamRepository;
	
	/**
	 * SeasonController constructor.
	 *
	 * @param SeasonRepositoryInterface $repository
	 * @param GroupRepositoryInterface  $groupRepository
	 * @param TeamRepositoryInterface   $teamRepository
	 */
	public function __construct (SeasonRepositoryInterface $repository, GroupRepositoryInterface $groupRepository, TeamRepositoryInterface $teamRepository)
	{
		$this->repository      = $repository;
		$this->groupRepository = $groupRepository;
		$this->teamRepository  = $teamRepository;
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index ()
	{
		$seasons = $this->repository->orderedAll();
		
		return view('admin.seasons.index', ['pageTitle' => 'Manage seasons', 'list' => $seasons]);
	}
	
	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create ()
	{
		return view('admin.seasons.create', ['pageTitle' => 'Create season']);
	}
	
	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store (Request $request)
	{
		$season = $this->repository->create($request->all());
		
		flash($season->name . ' season was created successfully', 'success');
		
		return redirect()->route('admin.season.create');
	}
	
	/**
	 * Display the specified resource.
	 *
	 * @param  $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show ($id)
	{
		$season = $this->repository->find($id);
		
		return view('admin.seasons.delete', ['pageTitle' => 'Delete ' . $season->name, 'season' => $season]);
	}
	
	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param $id
	 *
	 * @return \Illuminate\Http\Response
	 *
	 */
	public function edit ($id)
	{
		$season = $this->repository->find($id);
		
		$groupsList = $this->groupRepository->orderedAll();
		$teamsList  = $this->teamRepository->orderedAll();
		$service    = new GroupService();
		
		JavaScript::put([
			'groupsList' => $groupsList,
			'teamsList'  => $teamsList,
			'groups'     => $service->groupsWithTeams($season)
		]);
		
		return view('admin.seasons.edit', ['pageTitle' => 'Edit ' . $season->name, 'season' => $season]);
	}
	
	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param                           $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update (Request $request, $id)
	{
		$season = $this->repository->update($id, $request->all());
		
		$this->dispatch(new UpdateSeasonManagementJob($season, $request->input('groups')));
		
		flash($season->name . ' season was updated successfully', 'success');
		
		return redirect()->route('admin.season.edit', ['season' => $season->id]);
	}
	
	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy ($id)
	{
		$season = $this->repository->delete($id);
		
		flash($season->name . ' season was deleted successfully', 'success');
		
		return redirect()->route('admin.season.index');
	}
}

resources/views/admin/seasons/_form.blade.php
{!! BootForm::text('Name', 'name')->placeholder('Name')->required() !!}
{!! BootForm::date('Start date', 'start_date')->placeholder('Start date')->required() !!}
{!! BootForm::date('End date', 'end_date')->placeholder('End date')->required() !!}

resources/views/admin/seasons/_manage_groups.blade.php
<div class="form-group" ng-app="TGLoL" ng-controller="ManageGroups">
	<div class="col-sm-offset-2 col-sm-10">
		<select class="form-control" ng-options="group as group.name for group in groupsList track by group.id" ng-model="newGroup">
		
		</select>
		<div class="spacer-10"></div>
		
		<button class="btn btn-lg btn-success" ng-click="addGroup($event)">Add Group</button>
	</div>
	
	<div class="spacer-20"></div>
	
	<div class="col-sm-offset-2 col-sm-10 groups-table">
		<div class="text-center" ng-class="divSize" ng-if="groups.length > 0"
		     ng-repeat="group in groups track by $index">
			
			<div class="groups-name">
				<% group.name %>
			</div>
			<div class="teams">
				<div class="row team" ng-repeat="team in group.teams track by $index">
					<div class="col-md-10"><% team.name %></div>
					<div class="col-md-1 fake-button-container">
						<div class="fake-btn text-danger" ng-click="removeTeam($event, group.id, $index)"><i
								class="fa fa-times"></i></div>
					</div>
				</div>
				
				<div class="row">
					<div class="col-md-10">
						<select class="form-control"
						        ng-options="team as team.name for team in teamsList track by team.id"
						        ng-model="newTeam[group.id]">
						</select>
					</div>
					<div class="col-md-1 fake-button-container">
						<div class="fake-btn text-success" ng-click="addTeam($event, group.id)"><i class="fa fa-check"></i></div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="clearfix"></div>
	</div>
	
	<input type="hidden" name="groups" value="<% groups %>" />
</div>

resources/views/admin/seasons/create.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span><a href="{{ route('admin.season.index') }}">Manage seasons</a></span></li>
	<li><span>Create season</span></li>
@endsection

@section('admin_content')
	@include('components.admin.forms.header', ['title' =>  '<strong>Create</strong> Group'])
	
	{!! BootForm::openHorizontal(['sm' => [4, 8],'lg' => [2, 10]])->post()->action(route('admin.season.store')) !!}
	
	@include('admin.seasons._form')
	
	@include('components.admin.forms.footer', ['route' =>  route('admin.season.index'), 'submitText' => 'Create'])
	{!! BootForm::close() !!}
@endsection

resources/views/admin/seasons/delete.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span><a href="{{ route('admin.season.index') }}">Manage seasons</a></span></li>
	<li><span>{{ $pageTitle }}</span></li>
@endsection

@section('admin_content')
	@include('components.admin.delete', ['object' => $season, 'name' => $season->name, 'actionRoute' => route('admin.season.update', ['season' => $season->id]), 'indexRoute' => route('admin.season.index')])
@endsection

resources/views/admin/seasons/edit.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span><a href="{{ route('admin.season.index') }}">Manage seasons</a></span></li>
	<li><span>{{ $pageTitle }}</span></li>
@endsection

@section('admin_content')
	@include('components.admin.forms.header', ['title' =>  '<strong>Edit</strong> ' . $season->name])
	
	{!! BootForm::openHorizontal(['sm' => [4, 8],'lg' => [2, 10]])->put()->action(route('admin.season.update', ['season' => $season->id])) !!}
	{!! BootForm::bind($season) !!}
	
	@include('admin.seasons._form')
	
	<hr/>
	<h3>Manage groups and teams</h3>
	
	@include('admin.seasons._manage_groups')
	
	@include('components.admin.forms.footer', ['route' =>  route('admin.season.index'), 'submitText' => 'Edit'])
	{!! BootForm::close() !!}
@endsection

resources/views/admin/seasons/index.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span>Manage seasons</span></li>
@endsection

@section('admin_content')
	<a href="{{ route('admin.season.create') }}" class="theme_btn pull-right"><i class="fa fa-plus"></i> Create new season</a>
	<div class="spacer-20"></div>
	
	@include('flash::message')
	
	<div class="spacer-20"></div>
	
	@component('components.table')
		@slot('table_header')
			<th style="width: 50%">Name</th>
			<th style="width: 20%">Start date</th>
			<th style="width: 20%">End date</th>
			<th></th>
		@endslot
		
		@slot('table_body')
			@foreach($list as $entry)
				<tr class="text-center">
					<td>{{ $entry->name }}</td>
					<td>{{ $entry->present()->startDate }}</td>
					<td>{{ $entry->present()->endDate }}</td>
					<td>
						<a href="{{ route('admin.season.edit', ['season' => $entry->id]) }}" class="control-options primary"><i
								class="fa fa-pencil"></i></a>
						<a href="{{ route('admin.season.show', ['season' => $entry->id]) }}" class="control-options danger"><i
								class="fa fa-times"></i></a>
					</td>
				</tr>
			@endforeach
		@endslot
	@endcomponent
@endsection

@section('inline-scripts')
	<script type="text/javascript">
		$(document).ready(function () {
			$('.indexDataTables').DataTable({
				"dom": '<"top"f>rt<"bottom"pli><"clear">',
				"columns": [
					{"width": "45%", "targets": 0},
					{"width": "20%", "targets": 1},
					{"width": "20%", "targets": 2},
					{"searchable": false, "targets": 3}
				]
			});
		})
	</script>
@endsection