routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth', 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
	Route::resource('game', 'GameController', ['except' => 'index']);
	Route::resource('group', 'GroupController');
	Route::get('match/{match}/game/', ['as' => 'match.game.get', 'uses' => 'MatchController@getCreateGame']);
	Route::resource('match', 'MatchController');
	Route::resource('season', 'SeasonController');
	Route::resource('team', 'TeamController');
	Route::resource('player', 'PlayerController');
	Route::resource('user', 'UserController');
	Route::get('/', 'IndexController@dashboard')->name('dashboard');
});

Route::get('/img/{path}', ['as' => 'img', 'uses' => 'ImageController@show'])->where('path', '.*');

Route::get('match/{matchId}', 'HomeController@match')->name('match');
Route::get('player/{playerId}', 'HomeController@player')->name('player');
Route::get('players', 'HomeController@players')->name('players');
Route::get('schedule', 'HomeController@schedule')->name('schedule');
Route::get('standings', 'HomeController@standings')->name('standings');
Route::get('team/{teamId}', 'HomeController@team')->name('team');
Route::get('teams', 'HomeController@teams')->name('teams');
Route::get('/', 'HomeController@index')->name('home');

app/Match.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laracasts\Presenter\PresentableTrait;

/**
 * Class Match
 * @package App
 */
class Match extends Model
{
	use SoftDeletes;
	use PresentableTrait;
	
	/**
	 * The presenter class used to display data of this model.
	 *
	 * @var string
	 */
	protected $presenter = "App\Presenters\MatchPresenter";
	
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'matches';
	
	/**
	 * Attributes that should be mass-assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'season_id',
		'date',
		'time',
		'type',
		'best_of',
		'team1_id',
		'team2_id',
		'featured',
		'team1_score',
		'team2_score',
		'finished',
	];
	
	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = [];
	
	/**
	 * The attributes that should be casted to native types.
	 *
	 * @var array
	 */
	protected $casts = ['featured' => 'boolean'];
	
	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['date', 'created_at', 'updated_at', 'deleted_at'];
	
	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function games ()
	{
		return $this->hasMany(Game::class);
	}
	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function season ()
	{
		return $this->belongsTo(Season::class);
	}
	
	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasOne
	 */
	public function team1 ()
	{
		return $this->hasOne(Team::class, 'id', 'team1_id');
	}
	
	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasOne
	 */
	public function team2 ()
	{
		return $this->hasOne(Team::class, 'id', 'team2_id');
	}
	
	/**
	 * Select games that are marked as featured
	 *
	 * @param $query
	 *
	 * @return mixed
	 */
	public function scopeFeatured ($query)
	{
		return $query->where('featured', 1);
	}
	
	public function scopeFirstGame ($query)
	{
		return $query->games()->orderBy('match_number', 'asc')->first();
	}
	
	/**
	 * Select games that are ONLY in the future
	 *
	 * @param $query
	 *
	 * @return mixed
	 */
	public function scopeFuture ($query)
	{
		return $query->where('date', '>', Carbon::now()->format('Y-m-d'));
	}
	
	/**
	 * Select games that are ONLY in the past
	 *
	 * @param $query
	 *
	 * @return mixed
	 */
	public function scopePast ($query)
	{
		return $query->where('date', '<', Carbon::now()->format('Y-m-d'));
	}
	
	/**
	 * Select games that are in the past. Including same day
	 *
	 * @param $query
	 *
	 * @return mixed
	 */
	public function scopePastAndPresent ($query)
	{
		return $query->where('date', '<=', Carbon::now()->format('Y-m-d'));
	}
	
	/**
	 * Select games that in the future. Including same day
	 * @param $query
	 *
	 * @return mixed
	 */
	public function scopeFutureAndPresent ($query)
	{
		return $query->where('date', '>=', Carbon::now()->format('Y-m-d'));
	}
}

app/Http/Controllers/Admin/MatchController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Match;
use App\Repositories\Interfaces\GameRepositoryInterface;
use App\Repositories\Interfaces\MatchRepositoryInterface;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MatchController extends Controller
{
	/**
	 * @var MatchRepositoryInterface
	 */
	private $repository;
	/**
	 * @var GameRepositoryInterface
	 */
	private $gameRepository;
	
	/**
	 * MatchController constructor.
	 *
	 * @param MatchRepositoryInterface $repository
	 * @param GameRepositoryInterface  $gameRepository
	 */
	public function __construct (MatchRepositoryInterface $repository, GameRepositoryInterface $gameRepository)
	{
		$this->repository = $repository;
		$this->gameRepository = $gameRepository;
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index ()
	{
		$matches = $this->repository->orderedAll('desc');
		
		return view('admin.matches.index', ['pageTitle' => 'Manage matches', 'list' => $matches]);
	}
	
	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create ()
	{
		return view('admin.matches.create', ['pageTitle' => 'Create match']);
	}
	
	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store (Request $request)
	{
		$match = $this->repository->create($request->all());
		
		flash('Match #' . $match->id . ' was created successfully', 'success');
		
		return redirect()->route('admin.match.create');
	}
	
	/**
	 * Display the specified resource.
	 *
	 * @param  $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show ($id)
	{
		$match = $this->repository->find($id);
		
		return view('admin.matches.delete', ['pageTitle' => 'Delete ' . $match->name, 'match' => $match]);
	}
	
	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit ($id)
	{
		$match = $this->repository->find($id);
		$games = $this->gameRepository->byMatch($id);
		
		return view('admin.matches.edit', ['pageTitle' => 'Edit ' . $match->name, 'match' => $match, 'games' => $games]);
	}
	
	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param                           $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update (Request $request, $id)
	{
		$match = $this->repository->update($id, $request->all());
		
		flash('Match #' . $match->id . ' match was updated successfully', 'success');
		
		return redirect()->route('admin.match.edit', ['match' => $match->id]);
	}
	
	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy ($id)
	{
		$this->repository->delete($id);
		
		flash($match->name . ' match was deleted successfully', 'success');
		
		return redirect()->route('admin.match.index');
	}
	
	public function getCreateGame ($id)
	{
		$match = $this->repository->find($id);
		
		return view('admin.games.create', ['pageTitle' => 'Create game', 'match' => $match]);
	}
}

resources/views/admin/matches/_form.blade.php
@inject('service', 'App\Services\FormService')

{!! BootForm::date('Date', 'date')->required() !!}
<div class="form-group">
	<label class="col-sm-4 col-lg-2 control-label" for="time">Time</label>
	<div class="col-sm-8 col-lg-10">
		<input type="time" name="time" id="time" class="form-control" required="required" @if(isset($match))value="{{ $match->time }}"@endif>
	</div>
</div>
{!! BootForm::select('Season', 'season_id')->options($service->seasonsArray())->required() !!}
{!! BootForm::select('Team 1', 'team1_id')->options($service->teamsArray())->required() !!}
{!! BootForm::select('Team 2', 'team2_id')->options($service->teamsArray())->required() !!}
{!! BootForm::select('Type', 'type')->options($service->matchTypesArray())->required() !!}
<div class="form-group">
	<label class="col-sm-4 col-lg-2 control-label" for="best_of">Best of</label>
	<div class="col-sm-8 col-lg-10">
		<input type="number" name="best_of" id="best_of" class="form-control" required="required" @if(isset($match))value="{{ $match->best_of }}"@endif>
	</div>
</div>

{!! BootForm::checkbox('Featured', 'featured') !!}

resources/views/admin/matches/create.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span><a href="{{ route('admin.match.index') }}">Manage matchs</a></span></li>
	<li><span>Create match</span></li>
@endsection

@section('admin_content')
	@include('components.admin.forms.header', ['title' =>  '<strong>Create</strong> Match'])
	
	{!! BootForm::openHorizontal(['sm' => [4, 8],'lg' => [2, 10]])->post()->action(route('admin.match.store')) !!}
	
	@include('admin.matches._form')
	
	@include('components.admin.forms.footer', ['route' =>  route('admin.match.index'), 'submitText' => 'Create'])
	{!! BootForm::close() !!}
@endsection

resources/views/admin/matches/delete.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span><a href="{{ route('admin.match.index') }}">Manage matchs</a></span></li>
	<li><span>{{ $pageTitle }}</span></li>
@endsection

@section('admin_content')
	@include('components.admin.delete', ['object' => $match, 'name' => $match->present()->full_name, 'actionRoute' => route('admin.match.update', ['match' => $match->id]), 'indexRoute' => route('admin.match.index')])
@endsection

resources/views/admin/matches/edit.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span><a href="{{ route('admin.match.index') }}">Manage matches</a></span></li>
	<li><span>{{ $pageTitle }}</span></li>
@endsection

@section('admin_content')
	@include('components.admin.forms.header', ['title' =>  '<strong>Edit</strong> ' . $match->name])
	
	{!! BootForm::openHorizontal(['sm' => [4, 8],'lg' => [2, 10]])->put()->action(route('admin.match.update', ['match' => $match->id])) !!}
	{!! BootForm::bind($match) !!}
	
	@include('admin.matches._form')
	
	@include('components.admin.forms.footer', ['route' =>  route('admin.match.index'), 'submitText' => 'Edit'])
	{!! BootForm::close() !!}
	
	<hr/>
	<div class="spacer-10"></div>
	
	<h3>Manage games</h3>
	<div class="spacer-20"></div>
	
	<a href="{{ route('admin.match.game.get', ['match' => $match->id]) }}" class="pull-right btn btn-success btn-lg white-text"><i class="fa fa-plus"></i> Add game</a>
	<div class="spacer-10"></div>
	
	<div class="responsive-table">
		<table class="table table-striped">
			<thead>
				<tr>
					<th style="width: 15%;">Game #</th>
					<th style="width: 33%;">Red Team</th>
					<th style="width: 33%;">Blue Team</th>
					<th style="width: 5%;">Finished</th>
					<th style="width: 10%;"></th>
				</tr>
			</thead>
			<tbody>
				@foreach($games as $game)
					<tr>
						<td>{{ $game->match_number }}</td>
						<td>{{ $game->red_team->name }}</td>
						<td>{{ $game->blue_team->name }}</td>
						<td>{{ $game->finished }}</td>
						<td>
							<a href="{{ route('admin.game.edit', ['game' => $game->id]) }}"
						       class="control-options primary"><i class="fa fa-pencil"></i></a>
							<a href="{{ route('admin.game.show', ['game' => $game->id]) }}"
							   class="control-options danger"><i class="fa fa-times"></i></a>
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>
	</div>
@endsection

resources/views/admin/matches/index.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span>Manage matches</span></li>
@endsection

@section('admin_content')
	<a href="{{ route('admin.match.create') }}" class="theme_btn pull-right"><i class="fa fa-plus"></i> Create new match</a>
	<div class="spacer-20"></div>
	
	@include('flash::message')
	
	<div class="spacer-20"></div>
	
	@component('components.table')
	@slot('table_header')
	<th style="width: 15%">Date</th>
	<th style="width: 15%">Season</th>
	<th style="width: 27%">Team 1</th>
	<th style="width: 27%">Team 2</th>
	<th></th>
	@endslot
	
	@slot('table_body')
	@foreach($list as $entry)
		<tr>
			<td>{{ $entry->present()->formattedDate }}</td>
			<td class="text-center">{{ $entry->present()->seasonName }}</td>
			<td class="text-center">{{ $entry->present()->team1Name }}</td>
			<td class="text-center">{{ $entry->present()->team2Name }}</td>
			<td>
				<a href="{{ route('admin.match.edit', ['match' => $entry->id]) }}" class="control-options primary"><i
						class="fa fa-pencil"></i></a>
				<a href="{{ route('admin.match.show', ['match' => $entry->id]) }}" class="control-options danger"><i
						class="fa fa-times"></i></a>
			</td>
		</tr>
	@endforeach
	@endslot
	@endcomponent
@endsection

@section('inline-scripts')
	<script type="text/javascript">
		$(document).ready(function () {
			$('.indexDataTables').DataTable({
				"dom": '<"top"f>rt<"bottom"pli><"clear">',
				"columns": [
					{"width": "15%", "targets": 0},
					{"width": "15%", "targets": 1},
					{"width": "25%", "targets": 2},
					{"width": "25%", "targets": 3},
					{"searchable": false, "targets": 4}
				]
			});
		})
	</script>
@endsection