routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth', 'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
	Route::resource('game', 'GameController', ['except' => 'index']);
	Route::resource('group', 'GroupController');
	Route::get('match/{match}/game/', ['as' => 'match.game.get', 'uses' => 'MatchController@getCreateGame']);
	Route::resource('match', 'MatchController');
	Route::resource('season', 'SeasonController');
	Route::resource('team', 'TeamController');
	Route::resource('player', 'PlayerController');
	Route::resource('user', 'UserController');
	Route::get('/', 'IndexController@dashboard')->name('dashboard');
});

Route::get('/img/{path}', ['as' => 'img', 'uses' => 'ImageController@show'])->where('path', '.*');

Route::get('match/{matchId}', 'HomeController@match')->name('match');
Route::get('player/{playerId}', 'HomeController@player')->name('player');
Route::get('players', 'HomeController@players')->name('players');
Route::get('schedule', 'HomeController@schedule')->name('schedule');
Route::get('standings', 'HomeController@standings')->name('standings');
Route::get('team/{teamId}', 'HomeController@team')->name('team');
Route::get('teams', 'HomeController@teams')->name('teams');
Route::get('/', 'HomeController@index')->name('home');

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laracasts\Presenter\PresentableTrait;

class Team extends Model
{
	use SoftDeletes;
	use PresentableTrait;
	
	/**
	 * The presenter class used to display data of this model.
	 *
	 * @var string
	 */
	protected $presenter = "App\Presenters\TeamPresenter";
	
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'teams';
	
	/**
	 * Attributes that should be mass-assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'logo', 'description', 'created_at', 'updated_at'];
	
	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = [];
	
	/**
	 * The attributes that should be casted to native types.
	 *
	 * @var array
	 */
	protected $casts = [];
	
	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];
	
	/**
	 * Model's relationships
	 */
	public function groups ()
	{
		return $this->belongsToMany(Group::class, 'groups_teams', 'team_id', 'group_id');
	}
	
	public function players ()
	{
		return $this->hasMany(Player::class);
	}
	
	public function seasons ()
	{
		return $this->belongsToMany(Season::class, 'teams_seasons', 'team_id', 'season_id');
	}
	
	public function stats ()
	{
		return $this->hasMany(TeamStat::class);
	}

	public function scopeGroupsBySeason($query, $seasonId)
	{
		return $this->groups()->whereHas('seasons', function ($query) use($seasonId) {
		    $query->where('seasons.id', $seasonId);
		})->first();
	}
}

app/Http/Controllers/Admin/TeamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Jobs\UploadImageJob;
use App\Repositories\Interfaces\TeamRepositoryInterface;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TeamController extends Controller
{
	/**
	 * @var TeamRepositoryInterface
	 */
	private $repository;
	
	/**
	 * TeamController constructor.
	 *
	 * @param TeamRepositoryInterface $repository
	 */
	public function __construct (TeamRepositoryInterface $repository)
	{
		$this->repository = $repository;
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index ()
	{
		$teams = $this->repository->orderedAll();
		
		return view('admin.teams.index', ['pageTitle' => 'Manage teams', 'list' => $teams]);
	}
	
	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create ()
	{
		return view('admin.teams.create', ['pageTitle' => 'Create team']);
	}
	
	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store (Request $request)
	{
		$team = $this->repository->create($request->all());
		
		if ($request->hasFile('logo')) {
			$this->repository->updateLogo($team->id, $request->file('logo')->getClientOriginalName());
			
			$this->dispatch(new UploadImageJob($request->file('logo'), 'team/' . $team->id . '/logo/'));
		}
		
		flash($team->name . ' team was created successfully', 'success');
		
		return redirect()->route('admin.team.create');
	}
	
	/**
	 * Display the specified resource.
	 *
	 * @param  $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show ($id)
	{
		$team = $this->repository->find($id);
		
		return view('admin.teams.delete', ['pageTitle' => 'Delete ' . $team->name, 'team' => $team]);
	}
	
	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit ($id)
	{
		$team   = $this->repository->find($id);
		$roster = $this->repository->roster($id);
		
		return view('admin.teams.edit', ['pageTitle' => 'Edit ' . $team->name, 'team' => $team, 'roster' => $roster]);
	}
	
	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param                           $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update (Request $request, $id)
	{
		$team = $this->repository->update($id, $request->all());
		
		if ($request->hasFile('logo')) {
			$this->repository->updateLogo($team->id, $request->file('logo')->getClientOriginalName());
			
			$this->dispatch(new UploadImageJob($request->file('logo'), 'team/' . $team->id . '/logo/'));
		}
		
		flash($team->name . ' team was updated successfully', 'success');
		
		return redirect()->route('admin.team.edit', ['team' => $team->id]);
	}
	
	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy ($id)
	{
		$this->repository->delete($id);
		
		flash('Team was deleted successfully', 'success');
		
		return redirect()->route('admin.team.index');
	}
}

resources/views/admin/teams/_form.blade.php
{!! BootForm::text('Name', 'name')->placeholder('Name')->required() !!}
{!! BootForm::file('Logo', 'logo') !!}
@if(isset($team))
<div class="form-group"><label class="col-sm-4 col-lg-2 control-label" for="logo">Current logo</label>
	<div class="col-sm-8 col-lg-10">
		<img src="{{ route('img', ['path' => $team->present()->imageUrl . '?w=200']) }}" alt="{{ $team->name }}"/>
	</div>
</div>
@endif
{!! BootForm::textarea('Description', 'description')->placeholder('Description')->required() !!}

resources/views/admin/teams/create.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span><a href="{{ route('admin.team.index') }}">Manage teams</a></span></li>
	<li><span>Create team</span></li>
@endsection

@section('admin_content')
	@include('components.admin.forms.header', ['title' =>  '<strong>Create</strong> Team'])
	
	{!! BootForm::openHorizontal(['sm' => [4, 8],'lg' => [2, 10]])->post()->action(route('admin.team.store'))->multipart() !!}
	
	@include('admin.teams._form')
	
	@include('components.admin.forms.footer', ['route' =>  route('admin.team.index'), 'submitText' => 'Create'])
	{!! BootForm::close() !!}
@endsection

resources/views/admin/teams/delete.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span><a href="{{ route('admin.team.index') }}">Manage teams</a></span></li>
	<li><span>{{ $pageTitle }}</span></li>
@endsection

@section('admin_content')
	@include('components.admin.delete', ['object' => $team, 'name' => $team->name, 'actionRoute' => route('admin.team.update', ['team' => $team->id]), 'indexRoute' => route('admin.team.index')])
@endsection

resources/views/admin/teams/edit.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span><a href="{{ route('admin.team.index') }}">Manage teams</a></span></li>
	<li><span>Edit team</span></li>
@endsection

@section('admin_content')
	@include('components.admin.forms.header', ['title' =>  '<strong>Edit</strong> Team'])
	
	{!! BootForm::openHorizontal(['sm' => [4, 8],'lg' => [2, 10]])->put()->action(route('admin.team.update', ['team' => $team->id]))->multipart() !!}
	{!! BootForm::bind($team) !!}
	
	@include('admin.teams._form')
	
	@include('components.admin.forms.footer', ['route' =>  route('admin.team.index'), 'submitText' => 'Edit'])
	{!! BootForm::close() !!}
	
	<hr/>
	
	<h3 class="text-center">Team roster</h3>
	
	<div class="table-responsive">
		<table class="table table-striped text-center">
			<thead>
			<tr>
				<th>Player</th>
				<th>Role</th>
			</tr>
			</thead>
			<tbody>
			@foreach($roster as $player)
				<tr>
					<td>{!! $player->present()->url !!}</td>
					<td><strong>{{ $player->present()->primaryRole }}</strong>/
						{{ $player->present()->secondaryRole }}
					</td>
				</tr>
			@endforeach
			</tbody>
		</table>
	</div>
@endsection

resources/views/admin/teams/index.blade.php
@extends('layouts.admin')

@section('admin_breadcrumb')
	<li><span><a href="{{ route('admin.dashboard') }}">Admin</a></span></li>
	<li><span>Manage teams</span></li>
@endsection

@section('admin_content')
	<a href="{{ route('admin.team.create') }}" class="theme_btn pull-right"><i class="fa fa-plus"></i> Create new
		team</a>
	<div class="spacer-20"></div>
	
	@include('flash::message')
	
	<div class="spacer-20"></div>
	
	@component('components.table')
		@slot('table_header')
			<th style="width: 80%">Team</th>
			<th></th>
		@endslot
		
		@slot('table_body')
			@foreach($list as $entry)
				<tr class="text-center">
					<td>{{ $entry->name }}</td>
					<td>
						<a href="{{ route('admin.team.edit', ['team' => $entry->id]) }}" class="control-options primary"><i
								class="fa fa-pencil"></i></a>
						<a href="{{ route('admin.team.show', ['team' => $entry->id]) }}" class="control-options danger"><i
								class="fa fa-times"></i></a>
					</td>
				</tr>
			@endforeach
		@endslot
	@endcomponent
@endsection

@section('inline-scripts')
	<script type="text/javascript">
		$(document).ready(function() {
			$('.indexDataTables').DataTable({
				"dom": '<"top"f>rt<"bottom"pli><"clear">',
				"columns": [
					{"width": "80%", "targets": 0},
					{"searchable": false, "targets": 1}
				]
			});
		})
	</script>
@endsection